name: 'Sign Package'
description: 'Sign published actions using Cosign.'
author: 'Ruchika Jain'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/package-action'
    default: ${{ github.repository }}
  token:
    description: >
      Personal access token (PAT) used to fetch the repository with write package scope.
    default: ${{ github.token }}
  semver:
    description: 'Release version'
    default: '1.0.1'
  package-name: 
    description: 'The name of the package to be signed'
    default: ${{ github.repository }}
    
runs:
  using: 'node16'
  main: 'dist/index.js'
